import type { LatLon } from './types'
import type { OverpassResponse, OverpassElement } from './parse'
import { gridProviderFromArray } from '../terrain/gridded'
import type { ElevationProvider } from '../terrain/provider'

/**
 * The offline demo city — a real ~1km box baked into the repo (public/demo/paris.json,
 * generated by scripts/bake-demo-city.mjs).
 *
 * It exists so the very first screen never hangs on a live geocoder, Overpass or
 * terrain API: those are third-party and, under load, any of them can refuse every
 * mirror on a cold start, leaving the player on a dead menu. The baked asset is
 * served from the app's own origin — as reliable as the app itself — and flows
 * through the same parseOsm → build pipeline as a real city, so the demo looks and
 * drives like one. A share link or a resumed session still loads its real city;
 * the demo is the boot backdrop and the last-resort fallback.
 */

/** The query token that routes a load to the baked demo instead of the network. */
export const DEMO_CITY = '—demo—' // an em-dash sentinel: never a real place name

/** The shape of the baked asset file. */
export interface DemoAsset {
  name: string
  center: LatLon
  radius: number
  segments: number
  elements: OverpassElement[]
  heights: number[]
}

/** A parsed demo city: what {@link DEMO_CITY} feeds the loader in place of the network. */
export interface DemoCity {
  name: string
  center: LatLon
  osm: OverpassResponse
  provider: ElevationProvider
}

/**
 * Validate a baked asset and turn it into a loadable city — pure, so it can be
 * tested against a crafted asset and against the real committed file.
 *
 * The height grid must be exactly `(segments + 1)²`, or the interpolation would
 * read past its bounds and hand the car a surface that isn't there; a short or
 * malformed grid is rejected rather than silently driven on.
 */
export function parseDemoAsset(asset: DemoAsset): DemoCity {
  const { name, center, radius, segments, elements, heights } = asset
  if (!center || typeof center.lat !== 'number' || typeof center.lon !== 'number') {
    throw new Error('demo asset: missing center')
  }
  if (!(radius > 0) || !(segments > 0)) throw new Error('demo asset: bad radius/segments')
  if (!Array.isArray(elements) || elements.length === 0) throw new Error('demo asset: no OSM elements')
  const n = segments + 1
  if (!Array.isArray(heights) || heights.length !== n * n) {
    throw new Error(`demo asset: heights must be ${n * n} long, got ${heights?.length}`)
  }
  return {
    name,
    center,
    osm: { elements },
    provider: gridProviderFromArray(heights, radius, segments),
  }
}

let cached: Promise<DemoCity> | undefined

/**
 * Fetch and parse the baked demo city (memoised, so a re-load of the demo — boot,
 * then a failed city switch — never re-downloads it). Same-origin, so it is
 * reachable whenever the app itself loaded.
 */
export function fetchDemoCity(): Promise<DemoCity> {
  if (!cached) {
    cached = (async () => {
      const url = new URL('demo/paris.json', location.href)
      const res = await fetch(url.href)
      if (!res.ok) throw new Error(`demo city HTTP ${res.status}`)
      return parseDemoAsset((await res.json()) as DemoAsset)
    })().catch((e) => {
      cached = undefined // a failed fetch shouldn't poison later attempts
      throw e
    })
  }
  return cached
}
